// ignore_for_file: lines_longer_than_80_chars
//
// ⚠️  SETUP REQUIRED
// This file is auto-generated by the FlutterFire CLI.
// Run the following command once to create it for your Firebase project:
//
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// Until then this stub keeps the project compiling. Replace it with the
// real generated file before any Firebase features will work at runtime.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions: unsupported platform '
          '${defaultTargetPlatform.name}.\n'
          'Run `flutterfire configure` to generate the real options file.',
        );
    }
  }

  // ── Replace ALL values below with the output of `flutterfire configure` ───

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfOjfyY5kUG8e8aCHaDg8rmgQpStFjwsE',
    appId: '1:138787937708:android:ac3a70f5d179198102ee09',
    messagingSenderId: '138787937708',
    projectId: 'orbitapp-4e44f',
    storageBucket: 'orbitapp-4e44f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbvUjCByPom7ff7h7i2fP1ObRO_tWSaWE',
    appId: '1:138787937708:ios:575d9d6251cc700402ee09',
    messagingSenderId: '138787937708',
    projectId: 'orbitapp-4e44f',
    storageBucket: 'orbitapp-4e44f.firebasestorage.app',
    iosBundleId: 'com.orbit.app.orbitapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey:            'REPLACE_WITH_YOUR_MACOS_API_KEY',
    appId:             'REPLACE_WITH_YOUR_MACOS_APP_ID',
    messagingSenderId: 'REPLACE_WITH_YOUR_SENDER_ID',
    projectId:         'REPLACE_WITH_YOUR_PROJECT_ID',
    storageBucket:     'REPLACE_WITH_YOUR_STORAGE_BUCKET',
    iosBundleId:       'com.orbit.app.orbitapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey:            'REPLACE_WITH_YOUR_WEB_API_KEY',
    appId:             'REPLACE_WITH_YOUR_WEB_APP_ID',
    messagingSenderId: 'REPLACE_WITH_YOUR_SENDER_ID',
    projectId:         'REPLACE_WITH_YOUR_PROJECT_ID',
    storageBucket:     'REPLACE_WITH_YOUR_STORAGE_BUCKET',
    authDomain:        'REPLACE_WITH_YOUR_AUTH_DOMAIN',
    measurementId:     'REPLACE_WITH_YOUR_MEASUREMENT_ID',
  );
}